# Generated by Django 5.2.1 on 2025-07-18 20:46

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClockifySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api_key", models.CharField(max_length=100)),
                ("workspace_id", models.CharField(max_length=50)),
                ("user_id", models.CharField(max_length=50)),
                (
                    "hours_per_day",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("7.5"), max_digits=4
                    ),
                ),
            ],
        ),
    ]
