# Generated by Django 5.2.1 on 2025-08-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clockify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clockifysettings",
            name="total_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clockifysettings",
            name="hours_per_day",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
