# Generated by Django 5.2.1 on 2025-08-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clockify", "0002_clockifysettings_total_hours_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
            ],
        ),
    ]
