# Generated by Django 5.2.1 on 2026-07-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clockify", "0003_vacation"),
    ]

    operations = [
        migrations.AddField(
            model_name="clockifysettings",
            name="hour_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hourly rate in CZK, used to estimate earnings.",
                max_digits=8,
                null=True,
            ),
        ),
    ]
