# Generated by Django 4.2.5 on 2024-03-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_recipeitem_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeitem",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="recipe.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="recipestep",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="recipe.recipe",
            ),
        ),
    ]
