# Generated by Django 5.2.1 on 2025-11-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0007_tag_recipe_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipestep",
            name="text",
            field=models.TextField(max_length=1024),
        ),
    ]
