# Generated by Django 5.2.1 on 2026-08-02 20:34

from django.db import migrations, models

PANTRY_STAPLES = ["sůl", "pepř", "olej", "cukr"]
PURCHASE_UNITS = ["ks", "g", "kg", "ml", "l", "balení"]


def seed_data(apps, schema_editor):
    PantryStaple = apps.get_model("recipe", "PantryStaple")
    PurchaseUnit = apps.get_model("recipe", "PurchaseUnit")
    PantryStaple.objects.bulk_create(
        [PantryStaple(name=name) for name in PANTRY_STAPLES], ignore_conflicts=True
    )
    PurchaseUnit.objects.bulk_create(
        [PurchaseUnit(name=name) for name in PURCHASE_UNITS], ignore_conflicts=True
    )


def remove_data(apps, schema_editor):
    PantryStaple = apps.get_model("recipe", "PantryStaple")
    PurchaseUnit = apps.get_model("recipe", "PurchaseUnit")
    PantryStaple.objects.filter(name__in=PANTRY_STAPLES).delete()
    PurchaseUnit.objects.filter(name__in=PURCHASE_UNITS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0008_alter_recipestep_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="PantryStaple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="hide_from_tracking",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(seed_data, remove_data),
    ]
