# Generated by Django 5.2.1 on 2026-03-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConstructionQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.CharField(blank=True, max_length=500, null=True)),
                ("date_asked", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PriorityItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("priority_level", models.PositiveIntegerField(default=5)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="construction_docs/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-priority_level", "task_name"],
            },
        ),
    ]
