# Generated by Django 5.2.1 on 2026-04-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house_construction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorityitem",
            name="hide",
            field=models.BooleanField(default=False),
        ),
    ]
