# Generated by Django 5.2.1 on 2026-04-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house_construction", "0002_priorityitem_hide"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="gallery/full/")),
                (
                    "thumbnail",
                    models.ImageField(
                        editable=False, null=True, upload_to="gallery/thumbs/"
                    ),
                ),
                ("hide", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
