# Generated by Django 5.2.1 on 2026-04-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house_construction", "0003_projectimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/extra/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="house_construction.projectimage",
                    ),
                ),
            ],
        ),
    ]
